# Generated by Django 4.1 on 2022-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="createitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_no", models.IntegerField()),
                ("company_name", models.CharField(max_length=50)),
                ("medicine_name", models.CharField(max_length=50)),
                ("issue_date", models.IntegerField()),
                ("Expiry_date", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("uses", models.CharField(max_length=50)),
            ],
        ),
    ]
