# Generated by Django 4.1 on 2022-09-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacyapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="createpatients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("place", models.CharField(max_length=40)),
                ("phonenumber", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("medicine_puruchased", models.CharField(max_length=50)),
            ],
        ),
    ]
