# Generated by Django 4.1 on 2022-09-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacyapp", "0002_createpatients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createitem",
            name="Expiry_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="createitem",
            name="issue_date",
            field=models.DateField(),
        ),
    ]
